### ISSUE TITLE
Titanium 64bit support?

### ISSUE THREAD

**Issue by inakiabt** [JigarM/TiWebView#1]
Hi there!

Have you been able to get this running on the Ti 3.5.0 Alpha? By February, all modules need to be updated for 64bit support.

See: http://www.appcelerator.com/blog/2014/11/alpha-version-of-titanium-sdk-64-bit-support-now-available

**Comment by JigarM** [comment]
Hello Iñaki Abete,
I will check it soon and come back to this issue.
Thanks!

**Comment by JigarM** [comment]
I have changed this module to  Compatible with Alpha Version of Titanium SDK 64-bit.
